package com.funoble.myarstation.view;

public abstract class GameEventID {
	public static final int ESPRITEBUTTON_EVENT_GAME_OFFSET = 0;//游戏界面 精灵按钮事件 偏移量
	
	public static final int ESPRITEBUTTON_EVENT_GAME_MENU = ESPRITEBUTTON_EVENT_GAME_OFFSET + 0;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_X1 = ESPRITEBUTTON_EVENT_GAME_MENU + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_PLAYER0 = ESPRITEBUTTON_EVENT_GAME_X1 + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_PLAYER1 = ESPRITEBUTTON_EVENT_GAME_PLAYER0 + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_PLAYER2 = ESPRITEBUTTON_EVENT_GAME_PLAYER1 + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_PLAYER3 = ESPRITEBUTTON_EVENT_GAME_PLAYER2 + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_PLAYER4 = ESPRITEBUTTON_EVENT_GAME_PLAYER3 + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_PLAYER5 = ESPRITEBUTTON_EVENT_GAME_PLAYER4 + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_MY_HP = ESPRITEBUTTON_EVENT_GAME_PLAYER5 + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_PLAYER1_HP = ESPRITEBUTTON_EVENT_GAME_MY_HP + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_PLAYER2_HP = ESPRITEBUTTON_EVENT_GAME_PLAYER1_HP + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_PLAYER3_HP = ESPRITEBUTTON_EVENT_GAME_PLAYER2_HP + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_PLAYER4_HP = ESPRITEBUTTON_EVENT_GAME_PLAYER3_HP + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_PLAYER5_HP = ESPRITEBUTTON_EVENT_GAME_PLAYER4_HP + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_MY_NAME = ESPRITEBUTTON_EVENT_GAME_PLAYER5_HP + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_PLAYER1_NAME = ESPRITEBUTTON_EVENT_GAME_MY_NAME + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_PLAYER2_NAME = ESPRITEBUTTON_EVENT_GAME_PLAYER1_NAME + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_PLAYER3_NAME = ESPRITEBUTTON_EVENT_GAME_PLAYER2_NAME + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_PLAYER4_NAME = ESPRITEBUTTON_EVENT_GAME_PLAYER3_NAME + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_PLAYER5_NAME = ESPRITEBUTTON_EVENT_GAME_PLAYER4_NAME + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_DICECUP = ESPRITEBUTTON_EVENT_GAME_PLAYER5_NAME + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_READY = ESPRITEBUTTON_EVENT_GAME_DICECUP + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_CALL = ESPRITEBUTTON_EVENT_GAME_READY + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_CALL2 = ESPRITEBUTTON_EVENT_GAME_CALL + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_DUEL = ESPRITEBUTTON_EVENT_GAME_CALL2 + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_X23 = ESPRITEBUTTON_EVENT_GAME_DUEL + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_X24 = ESPRITEBUTTON_EVENT_GAME_X23 + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_X25 = ESPRITEBUTTON_EVENT_GAME_X24 + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_X26 = ESPRITEBUTTON_EVENT_GAME_X25 + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_X27 = ESPRITEBUTTON_EVENT_GAME_X26 + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_X28 = ESPRITEBUTTON_EVENT_GAME_X27 + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_DICE1 = ESPRITEBUTTON_EVENT_GAME_X28 + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_DICE2 = ESPRITEBUTTON_EVENT_GAME_DICE1 + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_DICE3 = ESPRITEBUTTON_EVENT_GAME_DICE2 + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_DICE4 = ESPRITEBUTTON_EVENT_GAME_DICE3 + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_DICE5 = ESPRITEBUTTON_EVENT_GAME_DICE4 + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_PLAYER1_DICE = ESPRITEBUTTON_EVENT_GAME_DICE5 + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_PLAYER2_DICE = ESPRITEBUTTON_EVENT_GAME_PLAYER1_DICE + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_PLAYER3_DICE = ESPRITEBUTTON_EVENT_GAME_PLAYER2_DICE + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_PLAYER4_DICE = ESPRITEBUTTON_EVENT_GAME_PLAYER3_DICE + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_PLAYER5_DICE = ESPRITEBUTTON_EVENT_GAME_PLAYER4_DICE + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_PLAYER1_DICEBG = ESPRITEBUTTON_EVENT_GAME_PLAYER5_DICE + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_PLAYER2_DICEBG = ESPRITEBUTTON_EVENT_GAME_PLAYER1_DICEBG + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_PLAYER3_DICEBG = ESPRITEBUTTON_EVENT_GAME_PLAYER2_DICEBG + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_PLAYER4_DICEBG = ESPRITEBUTTON_EVENT_GAME_PLAYER3_DICEBG + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_PLAYER5_DICEBG = ESPRITEBUTTON_EVENT_GAME_PLAYER4_DICEBG + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_X45 = ESPRITEBUTTON_EVENT_GAME_PLAYER5_DICEBG + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_X46 = ESPRITEBUTTON_EVENT_GAME_X45 + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_X47 = ESPRITEBUTTON_EVENT_GAME_X46 + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_BUYHP_CONFIRM = ESPRITEBUTTON_EVENT_GAME_X47 + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_BUYHP_RETURN = ESPRITEBUTTON_EVENT_GAME_BUYHP_CONFIRM + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_WHEEL = ESPRITEBUTTON_EVENT_GAME_BUYHP_RETURN + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_WHEEL_DICE = ESPRITEBUTTON_EVENT_GAME_WHEEL + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_CALL_CONFIRM = ESPRITEBUTTON_EVENT_GAME_WHEEL_DICE + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_CALL_RETURN = ESPRITEBUTTON_EVENT_GAME_CALL_CONFIRM + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_READYTIME = ESPRITEBUTTON_EVENT_GAME_CALL_RETURN + 1;//游戏界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAME_NAMECARD = ESPRITEBUTTON_EVENT_GAME_READYTIME + 1;//游戏界面 精灵按钮事件 名片
	public static final int ESPRITEBUTTON_EVENT_GAME_PLAYER0_NAMEBG = ESPRITEBUTTON_EVENT_GAME_NAMECARD + 1;//游戏界面 伪按钮 玩家0的名字底板
	public static final int ESPRITEBUTTON_EVENT_GAME_PLAYER1_NAMEBG = ESPRITEBUTTON_EVENT_GAME_PLAYER0_NAMEBG + 1;//游戏界面 伪按钮 玩家0的名字底板
	public static final int ESPRITEBUTTON_EVENT_GAME_PLAYER2_NAMEBG = ESPRITEBUTTON_EVENT_GAME_PLAYER1_NAMEBG + 1;//游戏界面 伪按钮 玩家0的名字底板
	public static final int ESPRITEBUTTON_EVENT_GAME_PLAYER3_NAMEBG = ESPRITEBUTTON_EVENT_GAME_PLAYER2_NAMEBG + 1;//游戏界面 伪按钮 玩家0的名字底板
	public static final int ESPRITEBUTTON_EVENT_GAME_PLAYER4_NAMEBG = ESPRITEBUTTON_EVENT_GAME_PLAYER3_NAMEBG + 1;//游戏界面 伪按钮 玩家0的名字底板
	public static final int ESPRITEBUTTON_EVENT_GAME_PLAYER5_NAMEBG = ESPRITEBUTTON_EVENT_GAME_PLAYER4_NAMEBG + 1;//游戏界面 伪按钮 玩家0的名字底板
	public static final int ESPRITEBUTTON_EVENT_GAME_BUYBEER_CONFIRM = ESPRITEBUTTON_EVENT_GAME_PLAYER5_NAMEBG + 1;//游戏界面 伪按钮 玩家0的名字底板
	public static final int ESPRITEBUTTON_EVENT_GAME_KICK = ESPRITEBUTTON_EVENT_GAME_BUYBEER_CONFIRM + 1;//踢人 游戏界面
	public static final int ESPRITEBUTTON_EVENT_GAME_MAKEFRIEND = ESPRITEBUTTON_EVENT_GAME_KICK + 1;//加好友 游戏界面
	public static final int ESPRITEBUTTON_EVENT_GAME_MENU_LEAVE = ESPRITEBUTTON_EVENT_GAME_MAKEFRIEND + 1;//菜单离开桌子 游戏界面
	public static final int ESPRITEBUTTON_EVENT_GAME_MENU_OTHERROOM = ESPRITEBUTTON_EVENT_GAME_MENU_LEAVE + 1;//菜单其它房间 游戏界面
	public static final int ESPRITEBUTTON_EVENT_GAME_MENU_RESUMEGAME = ESPRITEBUTTON_EVENT_GAME_MENU_OTHERROOM + 1;//菜单返回游戏 游戏界面
	public static final int ESPRITEBUTTON_EVENT_GAME_ITEM = ESPRITEBUTTON_EVENT_GAME_MENU_RESUMEGAME + 1;//道具 游戏界面
	public static final int ESPRITEBUTTON_EVENT_GAME_QUICK_DUEL = ESPRITEBUTTON_EVENT_GAME_ITEM + 1;//抢开 游戏界面
	public static final int ESPRITEBUTTON_EVENT_GAME_ITEM_HYPNOSIS = ESPRITEBUTTON_EVENT_GAME_QUICK_DUEL + 1;//催眠 游戏界面
	public static final int ESPRITEBUTTON_EVENT_GAME_ITEM_LIEKING = ESPRITEBUTTON_EVENT_GAME_ITEM_HYPNOSIS + 1;//千王 游戏界面
	public static final int ESPRITEBUTTON_EVENT_GAME_ITEM_SILENCE = ESPRITEBUTTON_EVENT_GAME_ITEM_LIEKING + 1;//封口 游戏界面
	public static final int ESPRITEBUTTON_EVENT_GAME_ITEM_QUICK_DUEL_CARD = ESPRITEBUTTON_EVENT_GAME_ITEM_SILENCE + 1;//抢开(卡片) 游戏界面
	public static final int ESPRITEBUTTON_EVENT_GAME_ITEM_COMBO_DUEL = ESPRITEBUTTON_EVENT_GAME_ITEM_QUICK_DUEL_CARD + 1;//连劈 游戏界面
	public static final int ESPRITEBUTTON_EVENT_GAME_ITEM_HUNT = ESPRITEBUTTON_EVENT_GAME_ITEM_COMBO_DUEL + 1;//追杀 游戏界面
	public static final int ESPRITEBUTTON_EVENT_GAME_ITEM_BG = ESPRITEBUTTON_EVENT_GAME_ITEM_HUNT + 1;//数量框 抢开按钮 游戏界面
	public static final int ESPRITEBUTTON_EVENT_GAME_ITEM_BG1 = ESPRITEBUTTON_EVENT_GAME_ITEM_BG + 1;//数量框 催眠 游戏界面
	public static final int ESPRITEBUTTON_EVENT_GAME_ITEM_BG2 = ESPRITEBUTTON_EVENT_GAME_ITEM_BG1 + 1;//数量框 千王 游戏界面
	public static final int ESPRITEBUTTON_EVENT_GAME_ITEM_BG3 = ESPRITEBUTTON_EVENT_GAME_ITEM_BG2 + 1;//数量框 封口 游戏界面
	public static final int ESPRITEBUTTON_EVENT_GAME_ITEM_BG4 = ESPRITEBUTTON_EVENT_GAME_ITEM_BG3 + 1;//数量框 连劈 游戏界面
	public static final int ESPRITEBUTTON_EVENT_GAME_ITEM_BG5 = ESPRITEBUTTON_EVENT_GAME_ITEM_BG4 + 1;//数量框 追杀 游戏界面
	public static final int ESPRITEBUTTON_EVENT_GAME_ITEM_TARGET_CONFIRM = ESPRITEBUTTON_EVENT_GAME_ITEM_BG5 + 1;//确认 选择目标  游戏界面
	
	
	public static final int ESPRITEBUTTON_EVENT_LOGIN_OFFSET = 10000;//登录界面 精灵按钮事件 偏移量
	
	public static final int ESPRITEBUTTON_EVENT_LOGIN_LOGIN = ESPRITEBUTTON_EVENT_LOGIN_OFFSET + 1;//登录界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_LOGIN_REGISTER = ESPRITEBUTTON_EVENT_LOGIN_OFFSET + 2;//登录界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_LOGIN_GUEST = ESPRITEBUTTON_EVENT_LOGIN_OFFSET + 3;//游客快进 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_LOGIN_AUTO_LOGIN = ESPRITEBUTTON_EVENT_LOGIN_OFFSET + 4; //自动登录
	
	
	public static final int ESPRITEBUTTON_EVENT_HOME_OFFSET = 20000;//大厅界面 精灵按钮事件 偏移量
	
	public static final int ESPRITEBUTTON_EVENT_HOME_QUICKSTART = ESPRITEBUTTON_EVENT_HOME_OFFSET + 12;//大厅界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_HOME_SELECTROOM = ESPRITEBUTTON_EVENT_HOME_OFFSET + 13;//大厅界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_HOME_RANK = ESPRITEBUTTON_EVENT_HOME_OFFSET + 14;//排行榜 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_HOME_MOTION = ESPRITEBUTTON_EVENT_HOME_OFFSET + 15;//活动精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_HOME_SHOP = ESPRITEBUTTON_EVENT_HOME_OFFSET + 16;//大厅界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_HOME_FRIEND = ESPRITEBUTTON_EVENT_HOME_OFFSET + 17;//好友 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_HOME_INFO = ESPRITEBUTTON_EVENT_HOME_OFFSET + 19;//个人资料 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_HOME_MORE = ESPRITEBUTTON_EVENT_HOME_OFFSET + 18;//更多 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_HOME_PHOTO = ESPRITEBUTTON_EVENT_HOME_OFFSET + 11;//拍照 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_HOME_GIFT = ESPRITEBUTTON_EVENT_HOME_OFFSET + 65;//领奖按钮
	public static final int ESPRITEBUTTON_EVENT_INVI_FRIEND = ESPRITEBUTTON_EVENT_HOME_OFFSET + 68;//邀请好友
	public static final int ESPRITEBUTTON_EVENT_HOME_CHANGEGIFT = ESPRITEBUTTON_EVENT_HOME_OFFSET + 76;//兑换礼品
	public static final int ESPRITEBUTTON_EVENT_HOME_CHANGE = ESPRITEBUTTON_EVENT_HOME_OFFSET + 77;//充值
	public static final int ESPRITEBUTTON_EVENT_HOME_MISSION = ESPRITEBUTTON_EVENT_HOME_OFFSET + 91;//充值

	public static final int ESPRITEBUTTON_EVENT_MORE_OFFSET = 25000; 
	public static final int ESPRITEBUTTON_EVENT_MORE_BACK = ESPRITEBUTTON_EVENT_MORE_OFFSET + 4;	//更多界面的返回按钮
	public static final int ESPRITEBUTTON_EVENT_MORE_SETTING = ESPRITEBUTTON_EVENT_MORE_OFFSET + 21;//设置
	public static final int ESPRITEBUTTON_EVENT_MORE_FEEDBACK = ESPRITEBUTTON_EVENT_MORE_OFFSET + 24;//反馈
	public static final int ESPRITEBUTTON_EVENT_MORE_HELP = ESPRITEBUTTON_EVENT_MORE_OFFSET + 23;//帮助
	public static final int ESPRITEBUTTON_EVENT_MORE_MESSAGE = ESPRITEBUTTON_EVENT_MORE_OFFSET + 22;//公告
	public static final int ESPRITEBUTTON_EVENT_MORE_GUIDE = ESPRITEBUTTON_EVENT_MORE_OFFSET + 25;//教程
	public static final int ESPRITEBUTTON_EVENT_MORE_SHOP = ESPRITEBUTTON_EVENT_MORE_OFFSET + 16;//商店
	public static final int ESPRITEBUTTON_EVENT_MORE_FRIEND = ESPRITEBUTTON_EVENT_MORE_OFFSET + 17;//好友
	public static final int ESPRITEBUTTON_EVENT_MORE_PHOTO = ESPRITEBUTTON_EVENT_MORE_OFFSET + 20;//拍照 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_MORE_INVI_FRIEND = ESPRITEBUTTON_EVENT_MORE_OFFSET + 68;//邀请好友
	public static final int ESPRITEBUTTON_EVENT_HOME_CHANGEACOUNT = ESPRITEBUTTON_EVENT_MORE_OFFSET + 90;//
	
	public static final int ESPRITEBUTTON_EVENT_WHEEL = 26000;
	public static final int ESPRITEBUTTON_EVNET_WHEEL_SHOUT = 26001;	//喊
	public static final int ESPRITEBUTTON_EVENT_WHEEL_CHOP = 26002;		//劈
	
	public static final int ESPRITEBUTTON_EVENT_BUTTON_PRECHOP = 26500; //抢劈按钮
	public static final int ESPRITEBUTTON_EVENT_BUTTON_CHAT = 26501;	//聊天按钮
	public static final int ESPRITEBUTTON_EVENT_BUTTON_MENU = 26502;	//菜单按钮
	public static final int ESPRITEBUTTON_EVENT_BUTTON_FACE = 26503;	//表情按钮
	public static final int ESPRITEBUTTON_EVENT_BUTTON_REBELCHOP = 26504;	//反劈按钮
	public static final int ESPRITEBUTTON_EVENT_BUTTON_ZHAI = 26505;	//喊斋按钮
	public static final int ESPRITEBUTTON_EVENT_BUTTON_LIGHTNING = 26506;	//雷击按钮
	public static final int ESPRITEBUTTON_EVENT_BUTTON_MISSION = 26507;	//任务按钮

	public static final int ESPRITEBUTTON_EVENT_PLAYER = 27000;
	
	public static final int ESPRITEBUTTON_EVENT_INIT_SYSTEM_BUTTON = 28000; //创建系统控件
	public static final int ESPRITEBUTTON_EVENT_SHOW_SYSTEM_BUTTON = 28001;	
	public static final int ESPRITEBUTTON_EVENT_HIDE_SYSTEM_BUTTON = 28002;	
	public static final int ESPRITEBUTTON_EVENT_DELET_SYSTEM_BUTTON = 28003;
	public static final int ESPRITEBUTTON_EVENT_SYSTEM_BUTTON_CHANGEXY = 28004; //改变系统控件的坐标
	public static final int ESPRITEBUTTON_EVENT_SHOW_BUYWINEDIALOG = 28005;	//显示买酒对话框
	public static final int ESPRITEBUTTON_EVENT_SHOW_CLEANDRUNKDIALOG = 28006;	//显示醒酒对话框
	public static final int ESPRITEBUTTON_EVENT_SHOW_STORE = 28007;//显示商城
	
	
	
	public static final int ESPRITEBUTTON_EVENT_REGISTER_OFFSET = 30000;//注册界面 精灵按钮事件 偏移量
	public static final int ESPRITEBUTTON_EVENT_REGISTER_CONFIRM = ESPRITEBUTTON_EVENT_REGISTER_OFFSET + 0;//注册界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_REGISTER_MSGBOX = ESPRITEBUTTON_EVENT_REGISTER_OFFSET + 1; //显示信息
	public static final int ESPRITEBUTTON_EVENT_REGISTER_REQUEST = ESPRITEBUTTON_EVENT_REGISTER_OFFSET + 2; //请求注册
	
	
	public static final int ESPRITEBUTTON_EVENT_CREATEROLE_OFFSET = 40000;//创建角色界面 精灵按钮事件 偏移量
	public static final int ESPRITEBUTTON_EVENT_CREATEROLE_CREATE = ESPRITEBUTTON_EVENT_CREATEROLE_OFFSET + 0;//创建角色界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_CREATEROLE_RECREATE = ESPRITEBUTTON_EVENT_CREATEROLE_OFFSET + 1;//创建角色界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_CREATEROLE_PLAYER1 = ESPRITEBUTTON_EVENT_CREATEROLE_OFFSET + 2;//创建角色界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_CREATEROLE_PLAYER2 = ESPRITEBUTTON_EVENT_CREATEROLE_OFFSET + 3;//创建角色界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_CREATEROLE_PLAYER3 = ESPRITEBUTTON_EVENT_CREATEROLE_OFFSET + 4;//创建角色界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_CREATEROLE_PLAYER4 = ESPRITEBUTTON_EVENT_CREATEROLE_OFFSET + 5;//创建角色界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_CREATEROLE_PLAYER5 = ESPRITEBUTTON_EVENT_CREATEROLE_OFFSET + 6;//创建角色界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_CREATEROLE_CREATE_SYSCOM = ESPRITEBUTTON_EVENT_CREATEROLE_OFFSET + 7; //创建系统控件
	public static final int ESPRITEBUTTON_EVENT_CREATEROLE_SHOW_SYSCOM = ESPRITEBUTTON_EVENT_CREATEROLE_OFFSET + 8; //显示系统控件
	public static final int ESPRITEBUTTON_EVENT_CREATEROLE_HIDE_SYSCOM = ESPRITEBUTTON_EVENT_CREATEROLE_OFFSET + 9; //隐藏系统控件
	public static final int ESPRITEBUTTON_EVENT_CREATEROLE_REQUEST = ESPRITEBUTTON_EVENT_CREATEROLE_OFFSET + 10; //请求创建角色
	public static final int ESPRITEBUTTON_EVENT_CREATEROLE_RENAME = ESPRITEBUTTON_EVENT_CREATEROLE_OFFSET + 11; //改名请求
	
	
	public static final int ESPRITEBUTTON_EVENT_INFO_OFFSET = 50000;//个人资料界面 精灵按钮事件 偏移量
	public static final int ESPRITEBUTTON_EVENT_INFO_RETURN = ESPRITEBUTTON_EVENT_INFO_OFFSET + 0;//返回 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_INFO_DETAIL = ESPRITEBUTTON_EVENT_INFO_OFFSET + 1; //详细数据
	public static final int ESPRITEBUTTON_EVENT_INFO_PHOTO = ESPRITEBUTTON_EVENT_INFO_OFFSET + 4;//照相
	public static final int ESPRITEBUTTON_EVENT_INFO_LEAVEMSG = ESPRITEBUTTON_EVENT_INFO_OFFSET + 5;//留言
	public static final int ESPRITEBUTTON_EVENT_INFO_CHANGEDICE = ESPRITEBUTTON_EVENT_INFO_OFFSET + 3;//改变骰子
	public static final int ESPRITEBUTTON_EVENT_INFO_PHRASE = ESPRITEBUTTON_EVENT_INFO_OFFSET + 73; //编辑常用语
	public static final int ESPRITEBUTTON_EVENT_INFO_SETTINGPWD = ESPRITEBUTTON_EVENT_INFO_OFFSET + 2; //设置密码
	
	public static final int ESPRITEBUTTON_EVENT_INFO_DETAIL_OFFSET = 51000;//个人资料界面-详细资料界面  精灵按钮事件 偏移量
	public static final int ESPRITEBUTTON_EVENT_INFO_DETAIL_CLOSE = ESPRITEBUTTON_EVENT_INFO_DETAIL_OFFSET + 1;//关闭
	public static final int ESPRITEBUTTON_EVENT_INFO_DETAIL_MODIFY = ESPRITEBUTTON_EVENT_INFO_DETAIL_OFFSET + 0;//修改
	
	
	public static final int ESPRITEBUTTON_EVENT_FRIEND_DETAIL_OFFSET = 60000;//好友详情界面 精灵按钮事件 偏移量
	public static final int ESPRITEBUTTON_EVENT_FRIEND_DETAIL_RETURN = ESPRITEBUTTON_EVENT_FRIEND_DETAIL_OFFSET + 0;//返回 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_FRIEND_DETAIL_DELFRIEND = ESPRITEBUTTON_EVENT_FRIEND_DETAIL_OFFSET + 9;//删好友
	public static final int ESPRITEBUTTON_EVENT_FRIEND_DETAIL_DING = ESPRITEBUTTON_EVENT_FRIEND_DETAIL_OFFSET + 7;	//顶
	public static final int ESPRITEBUTTON_EVENT_FRIEND_DETAIL_TRACE = ESPRITEBUTTON_EVENT_FRIEND_DETAIL_OFFSET + 8;//追踪
	public static final int ESPRITEBUTTON_EVENT_FRIEND_DETAIL_SHAKE = ESPRITEBUTTON_EVENT_FRIEND_DETAIL_OFFSET + 33;//醒酒
	public static final int ESPRITEBUTTON_EVENT_FRIEND_DETAIL_DELETE = ESPRITEBUTTON_EVENT_FRIEND_DETAIL_OFFSET + 9;//删除好友
	public static final int ESPRITEBUTTON_EVENT_FRIEND_GIVE_VIP_CONFIRM = ESPRITEBUTTON_EVENT_FRIEND_DETAIL_OFFSET + 65;//确认赠送vip
	public static final int ESPRITEBUTTON_EVENT_FRIEND_GIVE_VIP = ESPRITEBUTTON_EVENT_FRIEND_DETAIL_OFFSET + 6;//赠送vip
	public static final int ESPRITEBUTTON_EVENT_FRIEND_LEAVEMSG = ESPRITEBUTTON_EVENT_FRIEND_DETAIL_OFFSET + 5;//留言
	public static final int ESPRITEBUTTON_EVENT_FRIEND_DETAIL_INFO = ESPRITEBUTTON_EVENT_FRIEND_DETAIL_OFFSET + 1;//详细资料
	public static final int ESPRITEBUTTON_EVENT_FRIEND_INITSTSTEMCOM = ESPRITEBUTTON_EVENT_FRIEND_DETAIL_OFFSET + 100;//初始化控件
	public static final int ESPRITEBUTTON_EVENT_FRIEND_ZOOM = ESPRITEBUTTON_EVENT_FRIEND_DETAIL_OFFSET + 101;//初始化控件
	
	public static final int ESPRITEBUTTON_EVENT_TUTORIAL_OFFSET = 70000;	
	public static final int ESPRITEBUTTON_EVENT_TUTORIAL_RETURN = 70001;	//教程返回按钮
	public static final int ESPRITEBUTTON_EVENT_TUTORIAL_NEXT_ONE = 70002;	//教程下一步按钮
	public static final int ESPRITEBUTTON_EVENT_TUTORIAL_NEXT_TWO = 70003;	//教程下一步按钮
	
	public static final int ESPRITEBUTTON_EVENT_CHOOSEROOM_OFFSET = 80000;	//选择房间
	public static final int ESPRITEBUTTON_EVENT_CHOOSEROOM_TNTO = 80000 + 4;	//进入游戏
	public static final int ESPRITEBUTTON_EVENT_CHOOSEROOM_START = 80000 + 85;	//快速开始
	public static final int ESPRITEBUTTON_EVENT_CHOOSEROOM_SWITCH = 80000 + 87;	//撤换
	public static final int ESPRITEBUTTON_EVENT_CHOOSEROOM_HEAD = 80000 + 42;	//选择房间
	public static final int ESPRITEBUTTON_EVENT_CHOOSEROOM_TAB = 80000 + 78;	//
	public static final int ESPRITEBUTTON_EVENT_CHOOSEROOM_DETAIL = 80000 + 89;	//房间帮助
	
	public static final int ESPRITEBUTTON_EVENT_QUICKCHOOSEROOM_OFFSET = 90000;	//快速选择房间
	public static final int ESPRITEBUTTON_EVENT_QUICKCHOOSEROOM_STALL = ESPRITEBUTTON_EVENT_QUICKCHOOSEROOM_OFFSET + 0;	//大排档
	public static final int ESPRITEBUTTON_EVENT_QUICKCHOOSEROOM_KTV = ESPRITEBUTTON_EVENT_QUICKCHOOSEROOM_OFFSET + 1;	//ktv
	public static final int ESPRITEBUTTON_EVENT_QUICKCHOOSEROOM_BAR = ESPRITEBUTTON_EVENT_QUICKCHOOSEROOM_OFFSET + 2;	//酒吧
	public static final int ESPRITEBUTTON_EVENT_QUICKCHOOSEROOM_HOTEL = ESPRITEBUTTON_EVENT_QUICKCHOOSEROOM_OFFSET + 3;	//五星级
	public static final int ESPRITEBUTTON_EVENT_QUICKCHOOSEROOM_SEA = ESPRITEBUTTON_EVENT_QUICKCHOOSEROOM_OFFSET + 4;	//公海
	public static final int ESPRITEBUTTON_EVENT_QUICKCHOOSEROOM_ROYAL = ESPRITEBUTTON_EVENT_QUICKCHOOSEROOM_OFFSET + 5;	//皇家
	public static final int ESPRITEBUTTON_EVENT_QUICKCHOOSEROOM_LOVER = ESPRITEBUTTON_EVENT_QUICKCHOOSEROOM_OFFSET + 6;	//情侣
	public static final int ESPRITEBUTTON_EVENT_QUICKCHOOSEROOM_VIP = ESPRITEBUTTON_EVENT_QUICKCHOOSEROOM_OFFSET + 8;	//vip房间
	public static final int ESPRITEBUTTON_EVENT_QUICKCHOOSEROOM_COLSE = ESPRITEBUTTON_EVENT_QUICKCHOOSEROOM_OFFSET + 7;	//关闭
	
	
	public static final int ESPRITEBUTTON_EVENT_DETAILINFO_OFFSET = 100000;	//详细信息弹窗
	public static final int ESPRITEBUTTON_EVENT_DETAILINFO_RENAME = ESPRITEBUTTON_EVENT_DETAILINFO_OFFSET;	//改名
	public static final int ESPRITEBUTTON_EVENT_DETAILINFO_CLOSE = ESPRITEBUTTON_EVENT_DETAILINFO_OFFSET + 1;	//关闭
	public static final int ESPRITEBUTTON_EVENT_DETAILINFO_ADDFRIEND = ESPRITEBUTTON_EVENT_DETAILINFO_OFFSET + 4;	//加好友
	
	public static final int ESPRITEBUTTON_EVENT_GIFTS_OFFSET = 100100;	//送礼弹窗
	public static final int ESPRITEBUTTON_EVENT_GIFTS_CLOSE = ESPRITEBUTTON_EVENT_GIFTS_OFFSET + 0;	//关闭
	public static final int ESPRITEBUTTON_EVENT_GIFTS_CHOCOLATE = ESPRITEBUTTON_EVENT_GIFTS_OFFSET + 11;	//改名
	public static final int ESPRITEBUTTON_EVENT_GIFTS_PEER = ESPRITEBUTTON_EVENT_GIFTS_OFFSET + 12;	//关闭
	public static final int ESPRITEBUTTON_EVENT_GIFTS_BEAR = ESPRITEBUTTON_EVENT_GIFTS_OFFSET + 13;	//关闭
	public static final int ESPRITEBUTTON_EVENT_GIFTS_HEART = ESPRITEBUTTON_EVENT_GIFTS_OFFSET + 14;	//关闭
	public static final int ESPRITEBUTTON_EVENT_GIFTS_BOX = ESPRITEBUTTON_EVENT_GIFTS_OFFSET + 15;	//关闭
	public static final int ESPRITEBUTTON_EVENT_GIFTS_FLOWER = ESPRITEBUTTON_EVENT_GIFTS_OFFSET + 16;	//关闭
	public static final int ESPRITEBUTTON_EVENT_GIFTS_BALLOON = ESPRITEBUTTON_EVENT_GIFTS_OFFSET + 17;	//关闭
	public static final int ESPRITEBUTTON_EVENT_GIFTS_UNDERWEAR = ESPRITEBUTTON_EVENT_GIFTS_OFFSET + 18;	//关闭
	public static final int ESPRITEBUTTON_EVENT_GIFTS_VIP = ESPRITEBUTTON_EVENT_GIFTS_OFFSET + 19;	//关闭
	
	public static final int ESPRITEBUTTON_EVENT_BULLETIN = 100200;	//公告弹窗
	public static final int ESPRITEBUTTON_EVENT_BULLETIN_CLOSE = ESPRITEBUTTON_EVENT_BULLETIN + 0;	//公告弹窗关闭
	public static final int ESPRITEBUTTON_EVENT_BULLETIN_REWARD = ESPRITEBUTTON_EVENT_BULLETIN + 1;	//公告弹窗登录奖励
	public static final int ESPRITEBUTTON_EVENT_BULLETIN_NEWS = ESPRITEBUTTON_EVENT_BULLETIN + 2;	//公告弹窗公告
	public static final int ESPRITEBUTTON_EVENT_BULLETIN_GET = ESPRITEBUTTON_EVENT_BULLETIN + 3;	//公告弹窗领取
	public static final int ESPRITEBUTTON_EVENT_DAILYMISSION = ESPRITEBUTTON_EVENT_BULLETIN + 4;	//公告弹窗领取
	public static final int ESPRITEBUTTON_EVENT_BARMISSION = ESPRITEBUTTON_EVENT_BULLETIN + 5;	//公告弹窗领取
	
	public static final int ESPRITEBUTTON_EVENT_CHANGEDICE = 100300;	//选着骰子弹窗
	public static final int ESPRITEBUTTON_EVENT_CHANGEDICE_WHITE = ESPRITEBUTTON_EVENT_CHANGEDICE + 0;	//公告弹窗关闭
	public static final int ESPRITEBUTTON_EVENT_CHANGEDICE_PURPLE = ESPRITEBUTTON_EVENT_CHANGEDICE + 1;	//公告弹窗关闭
	public static final int ESPRITEBUTTON_EVENT_CHANGEDICE_BLUE = ESPRITEBUTTON_EVENT_CHANGEDICE + 2;	//公告弹窗关闭
	public static final int ESPRITEBUTTON_EVENT_CHANGEDICE_RED = ESPRITEBUTTON_EVENT_CHANGEDICE + 3;	//公告弹窗关闭
	public static final int ESPRITEBUTTON_EVENT_CHANGEDICE_YELLOW = ESPRITEBUTTON_EVENT_CHANGEDICE + 4;	//公告弹窗关闭
	public static final int ESPRITEBUTTON_EVENT_CHANGEDICE_COMMIT = ESPRITEBUTTON_EVENT_CHANGEDICE + 5;	//公告弹窗关闭
	
	public static final int ESPRITEBUTTON_EVENT_GAMEHALL = 100400;	//游戏大厅窗
	public static final int ESPRITEBUTTON_EVENT_GAMEHALL_GAMEA = ESPRITEBUTTON_EVENT_GAMEHALL + 90;//登录界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAMEHALL_GAMEB = ESPRITEBUTTON_EVENT_GAMEHALL + 91;//登录界面 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAMEHALL_GAMEC = ESPRITEBUTTON_EVENT_GAMEHALL + 92;//游客快进 精灵按钮事件 X0
	public static final int ESPRITEBUTTON_EVENT_GAMEHALL_GAMED = ESPRITEBUTTON_EVENT_GAMEHALL + 93; //自动登录
	
}
